### ISSUE TITLE
marginal performance boost from value types

### ISSUE THREAD

**Issue by tanner0101** [tanner0101/request-types#1]
<img width="1512" alt="screen shot 2017-03-27 at 2 11 32 pm" src="https://cloud.githubusercontent.com/assets/1342803/24358072/c92d49ae-12f7-11e7-8b68-d2c99dc6b9cf.png">

**Comment by jerrojelly** [comment]
Mind to post your benchmark scores for with and without inout?
System setup and environment?
CPU and memory usage?
